---

- name: download deb package
  get_url:
          url: http://get.code-industry.net/public/master-pdf-editor-4.1.30_qt5.amd64.deb
          dest: /tmp/master-pdf-editor-4.1.30_qt5.amd64.deb
  when: ansible_os_family == "Debian"

- name: install master-pdf-editor-4
  apt:
      deb: /tmp/master-pdf-editor-4.1.30_qt5.amd64.deb
  when: ansible_os_family == "Debian"

- name: remove deb file
  file:
       path: /tmp/master-pdf-editor-4.1.30_qt5.amd64.deb
       state: absent