---

- name: reading package list
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/Debian.yml"

- name: installing packages
  package: name={{ item }} state=installed
  with_items: "{{ packages }}"
