---

- name: download repository apt key
  get_url:
          url: https://download.sublimetext.com/sublimehq-pub.gpg
          dest: ~/sublimehq-pub.gpg
  when: ansible_os_family == "Debian"

- name: add repository apt key
  apt_key:
          file: ~/sublimehq-pub.gpg
          state: present
  when: ansible_os_family == "Debian"

- name: create apt source list
  template:
    src: ../templates/sublime-text.list
    dest: /etc/apt/sources.list.d/sublime-text.list
    mode: 0644
  when: ansible_distribution_release == "xenial"

- name: install sublime text
  apt:
      name=sublime-text
      state=installed
      update_cache=yes
  when: ansible_os_family == "Debian"

- name: remove apt key temp file
  file:
       path: ~/sublimehq-pub.gpg
       state: absent
- name: add sublime-text license file
  template:
           src: ../templates/License.sublime_license
           dest: /opt/sublime_text/License.sublime_license
           mode: 0666

- name: add license script
  template:
           src: ../templates/license_sublime.sh
           dest: /opt/sublime_text/license_sublime.sh
           mode: 0777