---

 - name: check aptitude package manager is installed and upgraded
   apt:
       name=aptitude
       state=latest
       update_cache=yes

 - name: performing full system upgrade
   apt:
       upgrade=full